#!/bin/bash
# GopakumarPB-on12-06-2020
#Modified for TDS_RPU_3.2 on 18-06-2020
# This script is expected to 
#create a short cut from Destop to
#Download and run an RPU after
#Version5-html
#Download RPU3.2 from Incometax Department 
#Through wget and show a download bar for the progress.
if [ ! -d ~/TDSTAX ]; then
mkdir ~/TDSTAX
wget -P ~/TDSTAX/ https://www.tin-nsdl.com/downloads/e-tds/download/TDS_RPU_3.2.zip 2>&1\
| sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --progress --title="Close the firefox if it is already opened!Downloading File..." 

#Start a loop testing if zenity is running, and if not kill wget
RUNNING=0
while [ $RUNNING -eq 0 ]
do
if [ -z "$(pidof zenity)" ]
then
  pkill wget
  RUNNING=1
fi
done 
#zip file in the TDSTAX folder renamed to RPU.zip
 mv ~/TDSTAX/*RPU*.zip ~/TDSTAX/RPU.zip &&
#unzipped to the same folder
unzip ~/TDSTAX/RPU.zip -d ~/TDSTAX/ &&
rm -rf ~/TDSTAX/RPU.zip &&
#unzipped folder renamed to RPU
mv ~/TDSTAX/*RPU* ~/TDSTAX/RPU &&
echo "#!/bin/bash" >> ~/Desktop/rpu.sh &&
echo "cd ~/TDSTAX/RPU/">> ~/Desktop/rpu.sh &&
FILE=$(find ~/TDSTAX/RPU -name "TDS_RPU_*")
echo "java -jar ${FILE##*/}">> ~/Desktop/rpu.sh &&
#An html message over firefox showing the sucess.
cat >~/Desktop/installed.html <<'_EOF'
<div class="header">
<body style="background-color:black;">
  <h1 style="color:#ff9933;">Now you have Installed the RPU !</h1>
  <h3 style="color:#ff9933;"><p>There is a file named rpu.sh in your Desktop.</p>
       <p> Right Click on it , go to properties, </p>
         <p>then to Permissions, put a tick mark to make it executable!</p>
         <p> close and double click on it !</p>
             </p> Please note that the version utilised by this script is RPU_3.2</p>
              </h3>
			</body>
			</div>
_EOF
firefox ~/Desktop/installed.html
#removed the html message file
rm -rf ~/Desktop/installed.html; else
cat > ~/Desktop/already.html <<'_EOF'
<div class="header">
<body style="background-color:#80BD9E;">
  <h1 style="color:#00293C">Sorry! The RPU is already in your system !</h1>
  <h3 style="color:#00293C"><p>If you are facing an installation error, </p>
<p>before clicking the run button, ensure the following:</p>
       <p>1.The file named<span style="color:#F52549">"rpu.sh"</span> is removed from your Desktop </p>
         <p>2. The folder named <span style="color:#F52549">"TDSTAX"</span> is deleted from your<span style="color:#F52549">/home folder</span></p>
         </h3>
</body>
</div>
_EOF
firefox ~/Desktop/already.html
rm -rf ~/Desktop/already.html
exit
fi
