#!/bin/bash
# GopakumarPB-on12-06-2020
#Further Modified for TDS_RPU_4.4 on 26-11-2022
# This script is expected to 
#Download RPU_4.4.zip from the wesite of 
#the Income tax Department Govt of India
#using wget.
#It is also expected to show a download bar showing the progress of the action. 
#A short cut for running the RPU is also created.
#
#
if [ ! -d ~/TDSTAX ]; then
mkdir ~/TDSTAX
wget -P ~/TDSTAX/ https://www.tin-nsdl.com/downloads/e-tds/download/RPU_4.4.zip 2>&1\
| sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --progress --title="Please wait till you see OK button as active..." --width=600 --height=400 

#Start a loop testing if zenity is running, and if not kill wget
RUNNING=0
while [ $RUNNING -eq 0 ]
do
if [ -z "$(pidof zenity)" ]
then
  pkill wget
  RUNNING=1
fi
done 
#zip file in the TDSTAX folder renamed to RPU.zip
 mv ~/TDSTAX/*RPU*.zip ~/TDSTAX/RPU.zip &&
#unzipped to the same folder
unzip ~/TDSTAX/RPU.zip -d ~/TDSTAX/ &&
rm -rf ~/TDSTAX/RPU.zip &&
#unzipped folder renamed to RPU
mv ~/TDSTAX/*RPU* ~/TDSTAX/RPU &&
echo "#!/bin/bash" >> ~/Desktop/rpu.sh &&
echo "cd ~/TDSTAX/RPU/">> ~/Desktop/rpu.sh &&
FILE=$(find ~/TDSTAX/RPU -name "TDS_RPU_*")
echo "java -jar ${FILE##*/}">> ~/Desktop/rpu.sh &&
chmod +x ~/Desktop/rpu.sh
#A zenity  message to show the sucess.
zenity --info --text '<span foreground="blue"  font="16">Now you have Installed the RPU !\nThere is a file named "rpu.sh" in your Desktop.\nRight Click on it , go to properties,\nthen to Permissions, \nput a tick mark to make it executable!
         close and double click on it !\nPlease note that the version utilised by this script is TDS_RPU_4.4!</span>' --width=600 --height=400; else
zenity --info --text '<span foreground="red"  font="16">  Sorry! The RPU is already in your system !\nIf you are facing an installation error,\n
before clicking the run button, ensure the following:\n1.The file named"rpu.sh" is removed from your Desktop\n2. The folder named "TDSTAX" is deleted from your /home folder!</span>\n\n<i></i>' --width=600 --height=200
exit
fi
